simonw/sqlite-utils

sqlite_utils/db.py

Older SQLite versions return a different set of columns from the PRAGMA we are using.

Make .indexes compatible with older SQLite versions

---

docs/python-api.rst

I noticed that both `.py` and `.db` were used in the docs and assumed you'd prefer `.db`.

:pencil: Updates my_database.py to my_database.db

---

docs/python-api.rst
sqlite_utils/db.py
tests/test_m2m.py

Work in progress: m2m() method for creating many-to-many records

---

sqlite_utils/cli.py
sqlite_utils/db.py
tests/test_cli.py
tests/test_enable_fts.py

This adds the option for a user to set up triggers in the database to keep their FTS table in sync with the parent table. 
Ref: https://sqlite.org/fts5.html#external_content_and_contentless_tables
I would prefer to make the creation of triggers the default behavior, but that will break existing usage where people have been calling `populate_fts` after inserting new rows.
I am happy to make changes to the PR as you see fit.

Add triggers while enabling FTS

---

MANIFEST.in
setup.py

Also exclude 'tests' from runtime installation.

Explicitly include tests and docs in sdist

---

sqlite_utils/cli.py
tests/test_cli.py

See commit messages for details. I ran into this while investigating another feature/issue.

Fix query command's support for DML

---

docs/cli.rst
docs/python-api.rst
sqlite_utils/cli.py
sqlite_utils/db.py
tests/test_cli.py

Deletes all rows in the table (if it exists) before inserting new rows.
SQLite doesn't implement a TRUNCATE TABLE statement but does optimize an
unqualified DELETE FROM.
This can be handy if you want to refresh the entire contents of a table
but a) don't have a PK (so can't use --replace), b) don't want the table
to disappear (even briefly) for other connections, and c) have to handle
records that used to exist being deleted.
Ideally the replacement of rows would appear instantaneous to other
connections by putting the DELETE + INSERT in a transaction, but this is
very difficult without breaking other code as the current transaction
handling is inconsistent and non-systematic.  There exists the
possibility for the DELETE to succeed but the INSERT to fail, leaving an
empty table.  This is …

Add insert --truncate option

---

docs/python-api.rst
sqlite_utils/db.py
tests/test_create.py

insert_all(..., alter=True) should work for new columns introduced after the first 100 records

---

sqlite_utils/db.py
tests/test_m2m.py

I was playing around with sqlite-utils, creating a Roam Research dogsheep-style importer for Datasette, and ran into a slight snag.
I wanted to use a generator to add an order column in an importer. It looked something like:
```
def order_generator(iterable, attr=None):
if attr is None:
attr = "order"
order: int = 0
for i in iterable:
i[attr] = order
order += 1
yield i
```
When I used this with `insert_all` and other things, it worked fine--but it didn't work as the `records` argument to `m2m`.  I dug into it, and sqlite-utils is explicitly checking if the records argument is a list or a tuple.  I flipped the check upside down, and now it checks if the argument is a mapping.  If it's a mapping, it wraps it in a list, otherwise it leaves it alone.
(I get that it might not really make sense …

Allow iterables other than Lists in m2m records

---

sqlite_utils/cli.py

The description for `create-table` was duplicated from `create-index`.

Fix incorrect create-table cli description

---

docs/changelog.rst
docs/cli.rst
sqlite_utils/cli.py
tests/test_cli.py
tests/test_cli_memory.py

Refs #272. Initial implementation only does CSV data, still needs:

sqlite-utils memory command for directly querying CSV/JSON data

---

.readthedocs.yaml
docs/Makefile
docs/conf.py
docs/index.rst
docs/python-api.rst
docs/reference.rst
sqlite_utils/db.py

Add reference page to documentation using Sphinx autodoc

---

docs/tutorial.ipynb
setup.py

While working on updating `sqlite-utils` for NixOS/Nixpkgs, I came a cross the following:
In 5ec6686153e29ae10d4921a1ad4c841f192f20e2, a new dependency was added on `dateutils` (https://pypi.org/project/dateutils/). 
I believe this is unintentional, and instead `python-dateutil` (https://pypi.org/project/python-dateutil/) was intended.
My reasoning is:
- `python-dateutil` is imported here in [recipes.py](https://github.com/simonw/sqlite-utils/blob/5ec6686153e29ae10d4921a1ad4c841f192f20e2/sqlite_utils/recipes.py#L1) 
- The `mypy` `type-python-dateutil` dependency in [setup.py](https://github.com/simonw/sqlite-utils/blob/5ec6686153e29ae10d4921a1ad4c841f192f20e2/setup.py#L36)
- `python-dateutil` is a dependency of `dateutils` as seen in the output in …

Use python-dateutil package instead of dateutils

---

sqlite_utils/db.py

the library deal with Postgres type jsonb as dictionary, add dict type as a TEXT for mapping to sqlite

Add dict type to be mapped as TEXT in sqllite

---

docs/cli.rst
docs/python-api.rst
sqlite_utils/cli.py
sqlite_utils/db.py
tests/test_analyze.py
tests/test_cli.py
tests/test_cli_bulk.py
tests/test_cli_insert.py
tests/test_create.py
tests/test_delete.py

`sqlite-utils bulk` command

---

.github/workflows/test-coverage.yml
docs/cli-reference.rst
docs/cli.rst
sqlite_utils/cli.py
tests/test_cli.py
tests/test_gis.py

Closes #398 
This adds SpatiaLite helpers to the CLI. 
```sh
sqlite-utils create database.db --enable-wal --init-spatialite
sqlite-utils add-geometry-column database.db table-name geometry --srid 4326 --not-null
sqlite-utils create-spatial-index database.db table-name geometry
```
Docs and tests are included.

Add SpatiaLite helpers to CLI

---

.gitignore

Closes #418 
This adds four files to `.gitignore`:
.hypothesis/
Pipfile
Pipfile.lock
pyproject.toml
Those are all generated in the course of development and testing.

Ignore common generated files

---

setup.py

Trying to get this to work with Pyodide.
Refs: https://github.com/simonw/click-default-group-wheel/issues/3

Depend on click-default-group-wheel

---

sqlite_utils/db.py
tests/test_duplicate.py

This PR addresses a feature request raised in issue #449. Specifically this PR adds a functionality that lets users duplicate a table via:
```python
table_new = db["my_table"].duplicate("new_table")
```
Test added in file `tests/test_duplicate.py`.
Happy to make changes to meet maintainers' feedback, if any.

Add duplicate table feature

---

.github/workflows/documentation-links.yml

Read the Docs repository was renamed from `readthedocs/readthedocs-preview` to `readthedocs/actions/`. Now, the `preview` action is under `readthedocs/actions/preview` and is tagged as `v1`

Use Read the Docs action v1 (#463)

---

docs/cli-reference.rst
docs/cli.rst

Work in progress, partly to test the ReadTheDocs preview link action.
Refs:
- #426
----
:books: Documentation preview :books:: https://readthedocs-preview--460.org.readthedocs.build/en/460/

Cross-link CLI to Python docs

---

sqlite_utils/db.py

sqlite "IS" is equivalent to SQL "IS NOT DISTINCT FROM"
closes #423

in extract code, check equality with IS instead of = for nulls

---

sqlite_utils/db.py
tests/test_fts.py

I haven't tested this yet but wanted to get a heads-up whether this kind of change would be useful or if I should just duplicate the function and tweak it within my code
----
:books: Documentation preview :books:: https://sqlite-utils--480.org.readthedocs.build/en/480/

search_sql add include_rank option

---

.github/workflows/publish.yml
.github/workflows/test.yml
sqlite_utils/cli.py
sqlite_utils/utils.py

----
:books: Documentation preview :books:: https://sqlite-utils--486.org.readthedocs.build/en/486/

progressbar for inserts/upserts of all fileformats, closes #485

---

sqlite_utils/utils.py

Does what it says and nothing else. This is the same set of paths as Datasette uses.
----
:books: Documentation preview :books:: https://sqlite-utils--536.org.readthedocs.build/en/536/

Add paths for homebrew on Apple silicon

---

sqlite_utils/db.py
tests/test_create.py

----
:books: Documentation preview :books:: https://sqlite-utils--537.org.readthedocs.build/en/537/

Support self-referencing FKs in `Table.create`

---

sqlite_utils/db.py
tests/test_default_value.py

Fixes #509, Fixes #336
Thanks for the great library!
I fixed a bug that `sqlite-utils transform` breaks DEFAULT values.
All tests already present passed  with no changes, and I added some tests for this PR.
In #509 case, fixed here.
```shell
$ sqlite3 test.db << EOF
CREATE TABLE mytable (
col1 TEXT DEFAULT 'foo',
col2 TEXT DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
)
EOF
$ sqlite3 test.db "SELECT sql FROM sqlite_master WHERE name = 'mytable';"
CREATE TABLE mytable (
col1 TEXT DEFAULT 'foo',
col2 TEXT DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
)
$ sqlite3 test.db "INSERT INTO mytable DEFAULT VALUES; SELECT * FROM mytable;"
foo|2022-12-21 01:15:39.669
$ sqlite-utils transform test.db mytable --rename col1 renamedcol1
$ sqlite3 test.db "SELECT sql FROM sqlite_master WHERE name = …
```

Fixes breaking DEFAULT values

---

sqlite_utils/db.py
tests/test_convert.py
tests/test_register_function.py

Fixes #525. All tests pass.
There's perhaps a better way to name lambdas? There could be a collision if a caller passes a function with name like `lambda_123456`.
SQLite [documentation](https://www.sqlite.org/appfunc.html) is a little, ah, lite on function name specs. If there is a character that can be used in place of underscore in a SQLite function name that is not permitted in a Python function identifier then that could be a good way to prevent accidental collisions. (I tried dash, colon, dot, no joy).
Otherwise, there is little chance of this happening and if it should happen the risk is mitigated by now throwing an exception in the case of a (name, arity) collision without `replace=True`.
----
:books: Documentation preview :books:: …

Fix repeated calls to `Table.convert()`

---

docs/cli-reference.rst
docs/cli.rst
docs/python-api.rst
sqlite_utils/cli.py
sqlite_utils/db.py
tests/test_analyze_tables.py

Analyze tables options: --common-limit, --no-most, --no-least

---

docs/plugins.rst
sqlite_utils/__init__.py
sqlite_utils/db.py
sqlite_utils/hookspecs.py
tests/test_plugins.py

Just like the [Datasette prepare_connection hook](https://docs.datasette.io/en/stable/plugin_hooks.html#prepare-connection-conn-database-datasette), this PR adds a similar hook for the `sqlite-utils` plugin system. 
The sole argument is `conn`, since I don't believe a `database` or `datasette` argument would be relevant here. 
I want to do this so I can release `sqlite-utils` plugins for my [SQLite extensions](https://github.com/asg017/sqlite-ecosystem), similar to the Datasette plugins I've release for them. 
An example plugin: https://gist.github.com/asg017/d7cdf0d56e2be87efda28cebee27fa3c
```bash
$ sqlite-utils install https://gist.github.com/asg017/d7cdf0d56e2be87efda28cebee27fa3c/archive/5f5ad549a40860787629c69ca120a08c32519e99.zip
$ sqlite-utils memory 'select hello("alex") as …
```

feat: Implement a prepare_connection plugin hook

---

sqlite_utils/db.py
tests/test_transform.py

I need to test that this works against:
- `rowid` tables
- Tables that have a column called `rowid` even though they are not rowid tables
----
:books: Documentation preview :books:: https://sqlite-utils--593.org.readthedocs.build/en/593/

.transform() now preserves rowid values, refs #592

---

sqlite_utils/db.py
sqlite_utils/utils.py

According to both [Debian](https://packages.debian.org/bookworm/arm64/libsqlite3-mod-spatialite/filelist) and [Ubuntu](https://packages.ubuntu.com/mantic/arm64/libsqlite3-mod-spatialite/filelist), the correct “target triple” for arm64 is `aarch64-linux-gnu`, so we should be looking in `/usr/lib/aarch64-linux-gnu` for `mod_spatialite.so`.
I can confirm that on both of my Debian arm64 SBCs, `libsqlite3-mod-spatialite` installs to that path.
```
$ ls -l /usr/lib/*/*spatial*
lrwxrwxrwx 1 root root      23 Dec  1  2022 /usr/lib/aarch64-linux-gnu/mod_spatialite.so -> mod_spatialite.so.7.1.0
lrwxrwxrwx 1 root root      23 Dec  1  2022 /usr/lib/aarch64-linux-gnu/mod_spatialite.so.7 -> mod_spatialite.so.7.1.0
-rw-r--r-- 1 root root 7348584 Dec  1  2022 …
```

Add spatialite arm64 linux path

---

sqlite_utils/cli.py

The issue is that underlying iterator is not fully consumed within the body of the `with file_progress()` block. Instead, that block creates generator expressions like `docs = (dict(zip(headers, row)) for row in reader)`
These iterables are consumed later, outside the `with file_progress()` block, which consumes the underlying iterator, and in turn updates the progress bar.
This means that the `ProgressBar.__exit__` method gets called before the last time the `ProgressBar.update` method gets called. The result is that the code to make the cursor invisible (inside the `update()` method) is called after the cleanup code to make it visible (in the `__exit__` method).
The fix is to move consumption of the `docs` iterators within the progress bar block. (
(An additional fix, to make …

Fixed issue #433 - CLI eats cursor

---

sqlite_utils/db.py

Adds `COLUMN_TYPE_MAPPING` for `TIME` fields that are mapped as `datetime.timedelta` for MySQL and json represantation for `datetime.timedelta` in order to fix #522
----
:books: Documentation preview :books:: https://sqlite-utils--596.org.readthedocs.build/en/596/

Fixes mapping for time fields related to mysql, closes #522

---

.github/workflows/publish.yml
.github/workflows/spellcheck.yml
.github/workflows/test-coverage.yml
.github/workflows/test.yml
setup.py
sqlite_utils/db.py

- #616
----
📚 Documentation preview 📚: https://sqlite-utils--617.org.readthedocs.build/en/617/

Drop support for Python 3.7

---

.github/workflows/test.yml
docs/cli-reference.rst
docs/python-api.rst
sqlite_utils/cli.py

I learned about `allow-prerelease: true` from https://github.com/dateutil/dateutil/pull/1337/files

Test against Python 3.13 pre-release

---

tests/test_cli.py

This removes the need to explicitly close files
and avoids accidental unclosed files
----
📚 Documentation preview 📚: https://sqlite-utils--618.org.readthedocs.build/en/618/

Use context managers for file writes in tests

---

docs/python-api.rst

Documented the use of delete_where, as shown in https://github.com/simonw/sqlite-utils/issues/159
----
📚 Documentation preview 📚: https://sqlite-utils--630.org.readthedocs.build/en/630/

Documented the use of `delete_where`

---

docs/cli.rst

----
📚 Documentation preview 📚: https://sqlite-utils--640.org.readthedocs.build/en/640/

typo in command name

---

docs/python-api.rst
sqlite_utils/db.py
tests/test_fts.py

----
📚 Documentation preview 📚: https://sqlite-utils--628.org.readthedocs.build/en/628/

add `include_rank` parameter to `Table.search`

---

docs/python-api.rst
sqlite_utils/cli.py
sqlite_utils/db.py
tests/test_cli.py
tests/test_create.py
tests/test_tracer.py
tests/test_upsert.py

Refs:
- #652
----
📚 Documentation preview 📚: https://sqlite-utils--653.org.readthedocs.build/en/653/

Use ON CONFLICT for upsert
