- docs/python-api.rst
- sqlite_utils/db.py
- tests/test_create.py
> db.add_foreign_keys() method

- docs/cli.rst
- docs/python-api.rst
- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/test_cli.py
- tests/test_create.py
> sqlite-utils index-foreign-keys / db.index_foreign_keys()

- docs/index.rst
- docs/python-api.rst
- sqlite_utils/db.py
- tests/test_extracts.py
> extracts= table parameter

- docs/python-api.rst
- sqlite_utils/db.py
- sqlite_utils/utils.py
- tests/test_create.py
- tests/test_introspect.py
- tests/test_update.py
> table.update() method

- docs/python-api.rst
- sqlite_utils/db.py
- tests/test_create.py
- tests/test_introspect.py
> Ability to introspect and run queries against views

- docs/python-api.rst
- sqlite_utils/db.py
- tests/test_introspect.py
> db.triggers and table.triggers introspection

- docs/cli.rst
- docs/python-api.rst
- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/test_cli.py
- tests/test_create.py
- tests/test_upsert.py
> Fixed implementation of upsert

- sqlite_utils/db.py
Add type conversion for Panda's Timestamp, if Panda library is present in system
(thanks for this project, I was about to do the same thing from scratch)
> Add type conversion for Panda's Timestamp

- docs/python-api.rst
- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_column_affinity.py
- tests/test_constructor.py
- tests/test_create.py
- tests/test_create_view.py
- tests/test_fts.py
- tests/test_introspect.py
- tests/test_tracer.py
Refs #150. Needs tests and documentation, including for the new `db.execute()` and `db.executescript()` methods.
> Tracer mechanism for seeing underlying SQL

- sqlite_utils/db.py
- tests/test_create.py
Addresses #145.
I think this should do the job.  If it meets with your approval I'll update this PR to include an update to the documentation -- I came across this bug while preparing a PR to update the documentation around `batch_size` in any event.
> Handle case where subsequent records (after first batch) include extra columns

- tests/test_create.py
One of these is my fault, and the other is one I just happened to come across.  They're harmless, but might as well be fixed.
> Typos in tests

- docs/python-api.rst
- sqlite_utils/db.py
- tests/test_register_function.py
- tests/test_transform.py
- tests/test_transform_table.py
Refs #114
- <strike>Support for `conversions=` parameter</strike>
> table.transform() method

- docs/python-api.rst
- sqlite_utils/db.py
- tests/test_transform.py
> Keyword only arguments for transform()

- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/test_extract.py
Takes my test down from ten minutes to four seconds. Refs #172.
> Much, much faster extract() implementation

- docs/cli.rst
- sqlite_utils/cli.py
- sqlite_utils/utils.py
- tests/test_cli.py
> Progress bar for sqlite-utils insert command

- docs/cli.rst
- docs/python-api.rst
- setup.py
- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/test_cli.py
- tests/test_fts.py
- tests/test_introspect.py
- tests/test_register_function.py
- tests/test_tracer.py
> table.search() improvements plus sqlite-utils search command

- docs/cli.rst
- docs/python-api.rst
- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/test_analyze_tables.py
> sqlite-utils analyze-tables command and table.analyze_column() method

- .github/workflows/test.yml
- tests/test_cli.py
- tests/test_insert_files.py
> Run tests against Ubuntu, macOS and Windows

- docs/changelog.rst
- docs/cli.rst
- docs/python-api.rst
Noticed a typo in the docs and followed that up with a spellcheck. Had to bite my tongue at some of the British spellings.
> Correct some typos

- docs/python-api.rst
> Typo in upsert example

- docs/cli.rst
- docs/python-api.rst
- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/test_cli.py
- tests/test_create.py
> Ability to add descending order indexes

- sqlite_utils/cli.py
This appears to be the [canonical solution](https://click.palletsprojects.com/en/7.x/documentation/#help-parameter-customization).
> add -h support closes #276

- docs/cli.rst
- sqlite_utils/cli.py
- tests/test_insert_files.py
> Ability to insert file contents as text, in addition to blob

- docs/cli.rst
> docs to dogs

- docs/cli.rst
Also testing https://docs.readthedocs.io/en/stable/pull-requests.html
> Link to installation instructions

- README.md
- docs/index.rst
Also testing fix for:
- https://github.com/readthedocs/readthedocs-preview/issues/10
----
:books: Documentation preview :books:: https://sqlite-utils--462.org.readthedocs.build/en/462/
> Discord badge

- .github/workflows/documentation-links.yml
- setup.py
> beanbag-docutils>=2.0

- .github/workflows/test.yml
- .gitignore
- docs/cli-reference.rst
- sqlite_utils/cli.py
- tests/ext.c
- tests/test_cli.py
Refs #470
----
:books: Documentation preview :books:: https://sqlite-utils--473.org.readthedocs.build/en/473/
> Support entrypoints for `--load-extension`

- docs/cli-reference.rst
- docs/cli.rst
- docs/python-api.rst
- sqlite_utils/cli.py
- sqlite_utils/db.py
- tests/test_create.py
- tests/test_introspect.py
Work in progress. Still needs documentation and tests (and to cover more cases of things that might have changed).
Refs:
- #467
----
:books: Documentation preview :books:: https://sqlite-utils--468.org.readthedocs.build/en/468/
> db[table].create(..., transform=True) and create-table --transform

- docs/_templates/base.html
- docs/cli.rst
Refs:
- #551
----
:books: Documentation preview :books:: https://sqlite-utils--553.org.readthedocs.build/en/553/
> Reformatted CLI examples in docs

- .github/workflows/test.yml
- docs/installation.rst
- docs/python-api.rst
- mypy.ini
- sqlite_utils/cli.py
- sqlite_utils/db.py
- sqlite_utils/utils.py
- tests/test_analyze.py
- tests/test_analyze_tables.py
- tests/test_cli.py
- tests/test_cli_memory.py
- tests/test_gis.py
Refs:
- #559 
----
:books: Documentation preview :books:: https://sqlite-utils--560.org.readthedocs.build/en/560/
> Use sqlean if available in environment

- docs/python-api.rst
- sqlite_utils/db.py
- tests/test_cli.py
- tests/test_create.py
- tests/test_extract.py
- tests/test_recipes.py
- tests/test_transform.py
Refs:
- #577
----
:books: Documentation preview :books:: https://sqlite-utils--584.org.readthedocs.build/en/584/
> .transform() instead of modifying sqlite_master for add_foreign_keys

- .github/workflows/publish.yml
- .github/workflows/spellcheck.yml
- .github/workflows/test-coverage.yml
- .github/workflows/test.yml
- setup.py
- sqlite_utils/db.py
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
----
📚 Documentation preview 📚: https://sqlite-utils--615.org.readthedocs.build/en/615/
> Run tests against ARM macos-14
